### ISSUE TITLE
Error occurs when user reached download limit

### ISSUE THREAD

**Issue by caseyscarborough** [byroot/ruby-osdb#21]
When a user has reached the download limit for OpenSubtitles.org for 24 hour period the following error occurs:

```
Something crashed.
Feel free to report the error here: https://github.com/byroot/ruby-osdb/issues
With the following debug informations:

Zlib::GzipFile::Error: not in gzip format:
/Users/Casey/.rvm/gems/ruby-2.1.5/gems/osdb-0.2.0/lib/osdb/sub.rb:49:in `initialize'
/Users/Casey/.rvm/gems/ruby-2.1.5/gems/osdb-0.2.0/lib/osdb/sub.rb:49:in `new'
/Users/Casey/.rvm/gems/ruby-2.1.5/gems/osdb-0.2.0/lib/osdb/sub.rb:49:in `block in fetch_body'
/Users/Casey/.rvm/gems/ruby-2.1.5/gems/osdb-0.2.0/lib/osdb/sub.rb:46:in `open'
/Users/Casey/.rvm/gems/ruby-2.1.5/gems/osdb-0.2.0/lib/osdb/sub.rb:46:in `fetch_body'
/Users/Casey/.rvm/gems/ruby-2.1.5/gems/osdb-0.2.0/lib/osdb/sub.rb:42:in `body'
/Users/Casey/.rvm/gems/ruby-2.1.5/gems/osdb-0.2.0/bin/getsub:143:in `download_sub!'
/Users/Casey/.rvm/gems/ruby-2.1.5/gems/osdb-0.2.0/bin/getsub:63:in `block in run!'
/Users/Casey/.rvm/gems/ruby-2.1.5/gems/osdb-0.2.0/bin/getsub:53:in `each'
/Users/Casey/.rvm/gems/ruby-2.1.5/gems/osdb-0.2.0/bin/getsub:53:in `run!'
/Users/Casey/.rvm/gems/ruby-2.1.5/gems/osdb-0.2.0/bin/getsub:157:in `<top (required)>'
/Users/Casey/.rvm/gems/ruby-2.1.5/bin/getsub:23:in `load'
/Users/Casey/.rvm/gems/ruby-2.1.5/bin/getsub:23:in `<main>'
/Users/Casey/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/Users/Casey/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by byroot** [comment]
I'll look into it thanks!
