### ISSUE TITLE
Error when using the options -s hi

### ISSUE THREAD

**Issue by evandrojr** [byroot/ruby-osdb#26]
-s, --search-by METHODS          Ordered list of search methods. h: by movie hash, i: by name on IMDB, n: by name on OSDb, p: by filename on OSDb. e.g -s hi . Default: h

j@fenix ~/p/ruby-osdb> ./bin/getsub -s hi ~/Downloads/
* Search subtitles for zzzzzzzzzzzzzzzzzzz
* Sub already there. To override it use --force

* Search subtitles for zzzzzz
* Sub already there. To override it use --force

* Search subtitles for sample

Something crashed.
Feel free to report the error here: https://github.com/byroot/ruby-osdb/issues
With the following debug informations:

NoMethodError: undefined method `map' for "":String:
/home/j/p/ruby-osdb/lib/osdb/server.rb:58:in `search_imdb'
/home/j/p/ruby-osdb/lib/osdb/search/imdb.rb:12:in `search_subs_for'
/home/j/p/ruby-osdb/lib/osdb/subtitle_finder.rb:13:in `block in find_sub_for'
/home/j/p/ruby-osdb/lib/osdb/subtitle_finder.rb:12:in `each'
/home/j/p/ruby-osdb/lib/osdb/subtitle_finder.rb:12:in `find_sub_for'
./bin/getsub:62:in `block in run!'
./bin/getsub:53:in `each'
./bin/getsub:53:in `run!'
./bin/getsub:157:in `<main>'

**Comment by evandrojr** [comment]
Fixed with commit ecc344b1af

https://github.com/byroot/ruby-osdb/commit/ecc344b1af5dba5faeb40b0ed240b4891bfbd07b
